INSERT INTO RESPONSE_SCHOOL_DETAILS VALUES(1, 'Tindivanam','St. Anns Hr Sec School',604001);
INSERT INTO RESPONSE_SCHOOL_DETAILS VALUES(2, 'Tindivanam','St. Joseph Hr Sec School',604002);
INSERT INTO RESPONSE_SCHOOL_DETAILS VALUES(3, 'Tindivanam','St. Philomenas Hr Sec School',604001);
INSERT INTO RESPONSE_SCHOOL_DETAILS VALUES(4, 'Tindivanam','St. Johns Hr Sec School',604003);